<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-24 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.6 on 2021-08-15 10:33

from django.db import migrations, models
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
=======
# Generated by Django 3.2.6 on 2021-08-15 10:33

from django.db import migrations, models
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
=======
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='HT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='HT', max_length=100)),
            ],
            options={
                'db_table': 'newslyht',
            },
        ),
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='TheHindu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='TheHindu', max_length=100)),
            ],
            options={
                'db_table': 'newslyth',
            },
        ),
        migrations.CreateModel(
            name='TOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='TOI', max_length=100)),
            ],
            options={
                'db_table': 'newslytoi',
            },
        ),
        migrations.AddConstraint(
            model_name='toi',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='TOI'),
        ),
        migrations.AddConstraint(
            model_name='thehindu',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='TH'),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ht',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='HT'),
=======
=======
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
<<<<<<< HEAD
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
=======
>>>>>>> de4868ddeec4c2907e30856003d2b79156cede3b
        ),
    ]
