# Generated by Django 3.2.6 on 2021-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
