# Generated by Django 3.2.6 on 2021-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_person_heading'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('heading',), name='headings'),
        ),
    ]
