# Generated by Django 3.2.6 on 2021-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_headings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='HT', max_length=100)),
            ],
            options={
                'db_table': 'NewslyHT',
            },
        ),
        migrations.CreateModel(
            name='TheHindu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='TheHindu', max_length=100)),
            ],
            options={
                'db_table': 'NewslyTH',
            },
        ),
        migrations.CreateModel(
            name='TOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('readmore', models.CharField(max_length=500)),
                ('channel', models.CharField(default='TOI', max_length=100)),
            ],
            options={
                'db_table': 'NewslyTOI',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
