# Generated by Django 3.2.6 on 2021-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210903_1207'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ht',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='HT'),
        ),
        migrations.AddConstraint(
            model_name='thehindu',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='TH'),
        ),
        migrations.AddConstraint(
            model_name='toi',
            constraint=models.UniqueConstraint(fields=('section', 'heading', 'headline', 'readmore'), name='TOI'),
        ),
    ]
