# Generated by Django 3.2.6 on 2021-09-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210910_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ht',
            table='newslyht',
        ),
        migrations.AlterModelTable(
            name='thehindu',
            table='newslyth',
        ),
        migrations.AlterModelTable(
            name='toi',
            table='newslytoi',
        ),
    ]
